# Generated by Django 5.2.1 on 2025-06-09 15:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tecnica', models.CharField(max_length=100)),
                ('descripcion', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(upload_to='piezas/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
