# Generated by Django 5.2.2 on 2025-06-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='receptor',
            new_name='destinatario',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='emisor',
            new_name='remitente',
        ),
        migrations.RenameField(
            model_name='mensaje',
            old_name='fecha',
            new_name='timestamp',
        ),
    ]
