# Generated by Django 5.2.2 on 2025-06-09 18:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='tecnica',
            field=models.CharField(default='técnica desconocida', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pieza',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
