# Generated by Django 5.2.3 on 2025-06-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pieza_tecnica_alter_pieza_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pieza',
        ),
    ]
